version: '3.8'

services:
  # Redis Database - Unchanged from original
  redis:
    image: redis:7.2-alpine
    container_name: geoai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - geoai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # FastAPI Backend ML Server - Updated with new Dockerfile path
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: geoai-backend
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
      - API_HOST=0.0.0.0
      - API_PORT=8002
      - FRONTEND_URL=http://frontend:3000
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./models:/app/models
    networks:
      - geoai-network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend 3D Interface - Unchanged from original
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: geoai-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8002
      - NODE_ENV=production
    networks:
      - geoai-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health.html"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy - Unchanged from original
  nginx:
    image: nginx:alpine
    container_name: geoai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - geoai-network
    depends_on:
      - backend
      - frontend
    profiles:
      - production
      
  # NEW: MaskRCNN service for 3D mask generation
  maskrcnn:
    build:
      context: .
      dockerfile: docker/Dockerfile.maskrcnn
    container_name: geoai-maskrcnn
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./models:/app/models
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - geoai-network
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # NEW: Streamlit Dashboard
  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit
    container_name: geoai-streamlit
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://backend:8002
    networks:
      - geoai-network
    depends_on:
      - redis
      - backend

  # NEW: Performance Monitoring Service
  monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile.monitor
    container_name: geoai-monitor
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - geoai-network
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

networks:
  geoai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16