[build]
  base = ""
  publish = "frontend/.next"
  command = "bash netlify-build.sh"

# Handle Python API in functions directory
[functions]
  directory = "api"
  node_bundler = "esbuild"

# Create redirect rules for API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://fusing-brains-and-boundaries.netlify.app/.netlify/functions"
  NEXT_PUBLIC_GEOAI_ENGINE_URL = "https://fusing-brains-and-boundaries.netlify.app/.netlify/functions"
  NODE_VERSION = "18"

# Override build command for the API to use custom requirements
[build.environment]
  PYTHON_VERSION = "3.9"
  PIP_FLAGS = "--no-cache-dir"

# Handle dependency failures gracefully
[plugins.inputs]
  pythonRequirements = "netlify.requirements.txt"
  
# Custom build plugin settings
[[plugins]]
package = "@netlify/plugin-nextjs"