name: Performance Testing with Meshery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  meshery-performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Meshery Performance Test
        uses: layer5io/meshery-performance-action@v0.4.0
        with:
          meshery_url: https://meshery.layer5.io
          performance_profile: "default"
          token: ${{ secrets.MESHERY_TOKEN }}
          service_mesh: "none"
          test_name: "GeoAI Model Performance Test"
